---
title: "visualizations"
author: "K. Enevoldsen"
date: "8/21/2021"
output: html_document
---

```{r packages}
library(tidyverse)
library(lubridate)
```

```{r data}
omnibus = read_csv("Omnibus/topics_omnibus.csv")
tabloid = read_csv("Tabloids/topics_tabloid.csv")
```



```{r aggregate}
omnibus_covid_topics <- c(6,22, 24, 30, 37, 41, 52, 70, 83, 88, 91, 92, 96)
tabloid_covid_topics <- c(11,28, 37, 49, 60, 72)

omni_topics = paste0("topic_", omnibus_covid_topics)
tabl_topics = paste0("topic_", tabloid_covid_topics)

agg_omni = omnibus %>% 
  mutate(day = floor_date(date, "day")) %>% 
  select(day, all_of(omni_topics)) %>% 
  group_by(day) %>% 
  summarise(across(starts_with("topic_"), ~ mean(.x, na.rm = TRUE)))

agg_tabl = tabloid %>% 
  mutate(day = floor_date(date, "day")) %>% 
  select(day, all_of(tabl_topics)) %>% 
  group_by(day) %>% 
  summarise(across(starts_with("topic_"), ~ mean(.x, na.rm = TRUE)))
```

```{r}

agg_omni %>% 
  mutate(covid = rowSums(across(starts_with("topic_")))) %>% 
  ggplot(aes(day, covid)) +
  geom_line(alpha = 0.5) +
  geom_smooth(span=0.15, color = "steelblue") + 
  theme_minimal() + 
  labs(y = "Prevalance of COVID19 in Omnibus media", x = "Date")


agg_tabl %>% 
  mutate(covid = rowSums(across(starts_with("topic_")))) %>% 
  ggplot(aes(day, covid)) +
  geom_line()

```



